[package]
distribution = "2201.13.0"
org = "ballerinax"
name= "googleapis.chat"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Communication/Google Chat", "Cost/Freemium", "Vendor/Google"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.chat"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "googleapis.chat-native"
version = "0.1.0-SNAPSHOT"
path = "../native/build/libs/googleapis.chat-native-0.1.0-SNAPSHOT.jar"

[build-options]
observabilityIncluded = true
